-----------------
--ENGLISH/DEFAULT
-----------------

VERSION		= "Version 4.0"
START_MSG	= "BetterEXP "..VERSION.." by Ture loaded! Update by Joelan (/bexp)"
BEXP_XP_STRING	= "you gain (.+) experience."
NORMAL_1	= "You are gaining normal experience!"
NORMAL_2	= "Gaining normal xp from kills"
RESTED_1	= "You are gaining rested experience!"
RESTED_2	= "Gaining 200% xp from kills"
BEXP_KILLS_TNL	= " kills to the next level"
BEXP_KILL_TNL	= "1 kill to the next level (congrats!)"
AVG_XP_MSG	= " avg xp per kill"
LOCKED_MSG	= " locked!"
UNLOCK_MSG	= " unlocked!"
COL_RES         = " colors reset!"
BAR_SIZE 	= " bar size reset!"
AVG_RES 	= "averages reset!"
HELP_1		= " locks experience bar in place."
HELP_2		= " unlocks experience bar."
HELP_3		= " displays help text."
HELP_4		= " change the color of the exp bar when not rested."
HELP_5		= " change the color of the exp bar when rested."
HELP_6		= " change the color of the bubble exp bar."
HELP_7		= " revert the colors to default values."
HELP_8		= " change the size of the exp bar"
HELP_9      	= " reset averages"
HELP_10		= " reset bar size"
--HELP_11		= " Horizontal Bar"
--HELP_12		= " Vertical Bar"
REMAINING_TXT	= " remaining"
RESTED_TXT	= " rested"
BAR_RESET 	= "bars reset to original size."
BEXP_CLOSE	= "Close"

