-- This file is automagically generated.
-- Please visit http://www.wowace.com/projects/bazooka/localization/
-- if you wish to help with the translation.

local L = LibStub("AceLocale-3.0"):NewLocale("Bazooka_Options", "esES")
if not L then return end

L["Adjust frames"] = "Ajustar marcos"
L["Area"] = "Área"
L["Background color"] = "Color de fondo"
L["Background settings"] = "Ajustes de Fondo"
L["Background texture"] = "Textura de fondo"
L["Background tile size"] = "Tamaño del mosaico de fondo"
L["Bar"] = "Barra"
L["Bars"] = "Barras"
L["Border color"] = "Color del borde"
L["Border texture"] = "Textura del borde"
L["Border thickness"] = "Grosor del borde"
L["Bottom"] = "Abajo"
L["Create new bar"] = "Crear nueva barra"
L["Disable mouse in combat"] = "Desactivar ratón en combate"
L["Disable mouse out of combat"] = "Desactivar ratón fuera de combate"
L["Disable tooltip"] = "Desactivar tooltip"
L["Disable tooltip in combat"] = "Desactivar tooltip en combate"
L["Enable background"] = "Activar fondo"
L["Enable highlight"] = "Activar resaltado"
L["Enable simple tooltips"] = "Activar tootips simples"
L["Enabled"] = "Activar"
L["Fade in combat"] = "Desvanecer en combate"
L["Fade opacity"] = "Opacidad del desvanecimiento"
L["Fade out of combat"] = "Desvanecer fuera de combate"
L["Fade-in duration"] = "Duración al aparecer"
L["Fade-out delay"] = "Retraso al desvanecerse"
L["Fade-out duration"] = "Duración al desvanecerse"
L["Font"] = "Fuente"
L["Font outline"] = "Borde de la fuente"
L["Font size"] = "Tamaño de la fuente"
L["Height"] = "Alto"
L["Hide tooltip on click"] = "Ocultar tooltip al hacer click"
L["Icon size"] = "Tamaño del icono"
L["Icon-text spacing"] = "Espaciado del texto del icono"
L["Label color"] = "Color de la etiqueta"
L["Left"] = "Izquierda"
L["Locked"] = "Bloqueado"
L["None"] = "Nada"
L["Normal"] = "Normal"
L["Opacity"] = "Opacidad"
L["Plugins"] = "Plugins"
L["Remove %s?"] = "¿Eliminar %s?"
L["Remove bar"] = "Eliminar barra"
L["Right"] = "Derecha"
L["Show icon"] = "Mostrar icono"
L["Show label"] = "Mostrar etiqueta"
L["Show text"] = "Mostrar texto"
L["Show title"] = "Mostrar título"
L["Text color"] = "Color del texto"
L["Top"] = "Arriba"
L["Width"] = "Ancho"

